config/routes.rb
Startuphackme::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :lessons
  resources :subscriber

  get 'privacy', :to => 'static#privacy'

  root :to => 'subscriber#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible 	:name, :week, :main_headline, :weekly_tagline, :first_ressource_headline,
  					:first_ressource_text, :second_ressource_headline, :second_ressource_text,
  					:third_ressource_headline, :third_ressource_text, :fourth_ressource_headline,
  					:fourth_ressource_text, :fifth_ressource_headline, :fifth_ressource_text,
  					:curator_name, :curator_description,
  					:first_ressource_headline_link, :second_ressource_headline_link, 
  					:third_ressource_headline_link, :fourth_ressource_headline_link,
  					:fifth_ressource_headline_link, :curator, :month, :description, :curator_organization,
  					:first_ressource_task, :second_ressource_task, :third_ressource_task,
  					:fourth_ressource_task, :fifth_ressource_task


  	  mount_uploader :curator, CuratorUploader



end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessible :email, :password, :password_confirmation, :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def after_sign_in_path_for(resource)
	'/lessons'
end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

before_filter :authenticate_user!, :except => [:index]

	def index
		@admin = if user_signed_in? then current_user.admin else nil end
		
		#sort descending by month and then by week number
		@lesson = Lesson.order("month ASC, week ASC")
		@month = @lesson

		@week = @lesson.last

		#creating the weeks_since_signup variable
		if user_signed_in? 
			then @sign_up = current_user.created_at - 7.days ## so the first lesson link is activeon sign-up
		else 
			@sign_up = (Time.now - 7.days) ## so the first lesson link is always clickable 
		end
		@full_weeks_since_signup = ((Time.now - @sign_up) / 60 / 60 / 24 / 7)

		#creating the loop counter inside the each_slice loop
		@loop_counter = 0

	end

	def show
		@lesson = Lesson.find(params[:id])
		@admin = if user_signed_in? then current_user.admin else nil end
	end

	def new
		@lesson = Lesson.new(params[:lesson])
	end

	def create
		@lesson = Lesson.create(params[:lesson])
		if @lesson.save
			flash[:notice] = 'It\'s all good buddy. We saved your lesson!'
			redirect_to @lesson
		else
			render 'new'
		end
	end

	def edit
		@lesson = Lesson.find(params[:id])
	end

	def update
		@lesson = Lesson.find(params[:id])
		if @lesson.update_attributes(params[:lesson])
			flash[:notice] = "Alright buddy, your Lesson is updated!"
			redirect_to(:action => 'show')
		else
			render 'edit'
		end
	end

	def destroy
		@lesson = Lesson.find(params[:id]).destroy
		flash[:notice] = "That's it - this lesson is completely gone!"
		redirect_to lessons_path
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/lessons'
  end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def privacy
	end

end

app/controllers/subscriber_controller.rb
class SubscriberController < ApplicationController

	def index
	end

	def show
	end

	def new
		@subscriber = Subscriber.new(params[:subscriber])
	end

	def create
		@subscriber = Subscriber.create(params[:subscriber])
		if @subscriber.save
			flash[:notice] = "You're subscribed - start learning now!"

			 # Tell the SubscriberMailer to send a welcome Email after save
			 #SubscriberMailer.welcome_email(@subscriber).deliver

			redirect_to new_user_registration_path( :email => params[:subscriber][:email])
		else
			render root_path
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscriber_helper.rb
module SubscriberHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Startup Hack - Weekly Lessons for Startup Entrepreneurs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <link href="assets/css/bootstrap-responsive.css" rel="stylesheet"> -->

  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-43318850-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>

</head>
<body>
  <div class="row-fluid">
    <div class="container span12">
      <header>
        <div class="content_wrap">
          <div class="logo">
            <%= link_to "startup hack", root_path, :class => "brand no-style-link" %>
          </div>
          <nav class="navbar navbar-fluid-top">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"></a>
            <div class="container-fluid nav-collapse">
              <ul class="nav pull-right">
                <li class="nav-line"><%= link_to "Lessons", lessons_path, :class => 'no-style-link'  %></li>
                <li class="nav-line"><a>|</a></li>
                <% if user_signed_in? %>
                <li class="nav-line"><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'no-style-link' %> </li>
                <% else %>
                <li class="nav-line"><%= link_to "Sign in", new_user_session_path, :class => 'no-style-link' %> </li>
                <% end %>
              </ul>
            </div> <!-- end container-fluid -->
          </nav>
        </div> <!-- end content_wrap -->
      </header>
      <hr class="hr_main">
      <hr class="hr_shadow">
      <%= yield %>
    </div>
  </div>
  <% if @page_title == "Sign" %>
    <div class="navbar navbar-fixed-bottom">
        <footer class="text-center">
          Startup Hack. &copy;2013. Proudly Hacked in Boston, Massachusetts |
          <%= link_to('Privacy', privacy_path, :class => 'footer-spacing footer-link') %> |
          <%= mail_to('hello@startuphack.it', 'Contact', :class => 'footer-spacing footer-link') %>
          <p /> 
        </footer>
    </div>
    <% else %>
        <footer class="text-center">
          Startup Hack. &copy;2013. Proudly Hacked in Boston, Massachusetts |
          <%= link_to('Privacy', privacy_path, :class => 'footer-spacing footer-link') %> |
          <%= mail_to('hello@startuphack.it', 'Contact', :class => 'footer-spacing footer-link') %>
          <p />    
        </footer>
    <% end %>
    </div>
  </div>
</body>
</html>

app/views/lessons/_lesson_form.html.erb
  <%= f.error_notification %>
  <%= f.input :week, label: 'Which week is this lesson for?'  %>
  <p>
  <%= f.input :month, label: 'Which month is this lesson for ->  Write 1 for the first month?'  %>



  <%= f.input :name, label: 'Lesson Name - Do not use'  %>
  <%= f.input :main_headline, label: 'Main Headline - Lesson Detail Page', as: :text, input_html: { rows: "3" } %>
  <%= f.input :description, label: 'What is this lesson about?', as: :text, input_html: { rows: "3" } %>
  <%= f.input :weekly_tagline, label: 'Weekly Tagline - Lesson Overview Page', as: :text, input_html: { rows: "3" } %>  
  </br>
  </br>
  <%= f.input :first_ressource_headline, label: 'First Ressource Headline' %>
  <%= f.input :first_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  <%= f.input :first_ressource_headline_link, label: 'First Ressource Link' %>
  </br>
  </br>
  <%= f.input :second_ressource_headline, label: 'Second Ressource Headline' %>
  <%= f.input :second_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  <%= f.input :second_ressource_headline_link, label: 'Second Ressource Link' %>
  </br>
  </br>  
  
  <%= f.input :third_ressource_headline, label: 'Third Ressource Headline' %>
  <%= f.input :third_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  <%= f.input :third_ressource_headline_link, label: 'Third Ressource Link' %>
  </br>
  </br>  
  
  <%= f.input :fourth_ressource_headline, label: 'Fourth Ressource Headline' %>
  <%= f.input :fourth_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  <%= f.input :fourth_ressource_headline_link, label: 'Fourth Ressource Link' %>
  </br>
  </br>  

  <%= f.input :fifth_ressource_headline, label: 'Fifth Ressource Headline' %>
  <%= f.input :fifth_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  <%= f.input :fifth_ressource_headline_link, label: 'Fifth Ressource Link' %>
  </br>
  </br>
    
  <%= f.input :curator_name, label: 'Name of weekly Curator' %>
  <%= f.input :curator_organization, label: 'Organization of weekly Curator' %>
  <%= f.input :curator_description, label: 'Bio of weekly curator', as: :text, input_html: { rows: "3" } %>
  <%= f.input :curator, label: 'Image of the curator' %>
	</br>

app/views/lessons/_lesson_form_new.erb
<div class="container">

		<div class="span6 offset">
			<%= f.error_notification %>
			<h2>Basic info for every lesson</h2>
			<div class="row">
				<div class="span4 offset2">
			  <%= f.input :month, label: 'Which month is this lesson for ->  Write 1 for the first month?'  %>
			  	</div>
			  	<div class="span4 offset2">
			   <%= f.input :weekly_tagline, label: 'Weekly Tagline - For the Lesson Overview Page', as: :text, input_html: { rows: "3" } %>
			  	</div>
			</div>
		</div>
</div>
<hr>

	<div class="row box-to">
		<section class="span4 offset1">
				<h1>1</h1>
				<hr>
				<h2>
					<%= f.input :first_ressource_headline, label: 'First Ressource Headline' %>
				</h2>
				<p>
					<%= f.input :first_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
				</p>
					<%= f.input :first_ressource_task, label: 'First Task', as: :text, input_html: { rows: "3" } %>
				</p>				
				<p>
 					<%= f.input :first_ressource_headline_link, label: 'First Ressource Link' %>
				</p>
			</br>
				<h1>2</h1>
				<hr>
				<h2>
					<%= f.input :second_ressource_headline, label: 'Second Ressource Headline' %>
				</h2>
				<p>
					<%= f.input :second_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
				</p>
					<%= f.input :second_ressource_task, label: 'Second Task', as: :text, input_html: { rows: "3" } %>
				</p>				
				<p>
					<%= f.input :second_ressource_headline_link, label: 'Second Ressource Link' %>
				</p>
			</br>
				<h1>3</h1>
				<hr>
				<h2>
  					<%= f.input :third_ressource_headline, label: 'Third Ressource Headline' %>
				</h2>
				<p>
  					<%= f.input :third_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
  				</p>
					<%= f.input :third_ressource_task, label: 'Third Task', as: :text, input_html: { rows: "3" } %>
				</p>  				
  				<p>
 					<%= f.input :third_ressource_headline_link, label: 'Third Ressource Link' %>
  				</p>
			</br>
				<h1>4</h1>
				<hr>
				<h2>
 					<%= f.input :fourth_ressource_headline, label: 'Fourth Ressource Headline' %>
				</h2>
				<p>
					<%= f.input :fourth_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
				</p>
					<%= f.input :fourth_ressource_task, label: 'Fourth Task', as: :text, input_html: { rows: "3" } %>
				</p>				
				<p>
 					<%= f.input :fourth_ressource_headline_link, label: 'Fourth Ressource Link' %>
				</p>
			</br>
				<h1>5</h1>
				<hr>
				<h2>
 					<%= f.input :fifth_ressource_headline, label: 'Fifth Ressource Headline' %>
				</h2>
				<p>
					<%= f.input :fifth_ressource_text, label: 'Description', as: :text, input_html: { rows: "3" } %>
				</p>
					<%= f.input :fifth_ressource_task, label: 'Fifth Task', as: :text, input_html: { rows: "3" } %>
				</p>				
				<p>
 					<%= f.input :fifth_ressource_headline_link, label: 'Fifth Ressource Link' %>
				</p>	

		</section>

		<section class="span5 offset1 lesson_summary">

			<h1 class="lesson-week">
				Week   
				<%= f.input :week, label: 'Which week is this lesson for?'  %>

			</h1>
			<h2 class="lesson-main-headline">
  			<%= f.input :main_headline, label: 'Main Headline - Lesson Detail Page', as: :text, input_html: { rows: "3" } %>
			</h2>
			<h2>
  				<%= f.input :description, label: 'What is this lesson about?', as: :text, input_html: { rows: "8" } %>	
  			</h2>
  			<hr class="hr_main">


			<div class="row">
				<article class="curator_block">
				<h2 class="lesson-main-headline">Your Curator</h2>
					<p> 
						<%= f.input :curator, label: 'Image of the curator' %>
					</p>
					<h1> 
						<%= f.input :curator_name, label: 'Name of weekly Curator' %>
					</h1>
					<h2>
  						<%= f.input :curator_organization, label: 'Organization of weekly Curator' %>
  					</h2>
				<div class="span">
					<p>
 						<%= f.input :curator_description, label: 'Bio of weekly curator', as: :text, input_html: { rows: "10" } %>
 					</p>
				</div>
				</article>
			</div>
		</div>

app/views/lessons/edit.html.erb
<div class="container">

  <h1>Create a new Lesson</h1>

<%= simple_form_for @lesson, :url => {:action => 'update', :id => @lesson.id}, :method => 'put', :html => {:class => 'form-horizontal', :multipart => true } do |f| %>

  <%= render(:partial => 'lesson_form_new', :locals => {:f => f}) %>

  <%= f.button :submit, class: "btn btn-primary", value: "Update Lesson" %>
<% end %>

</div>

app/views/lessons/index.html.erb
<script type="text/javascript">
    $(window).load(function(){
        $('#lesson-social').modal('show');
    });
</script>

     
<!-- Modal -->
<% if user_signed_in? && (current_user.created_at + 5.seconds) > Time.now %>
	<div id="lesson-social" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
	    <div class="modal-header text-center">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel" class="header-modal-message">Share the Love</h3>
	    </div>
	    <div class="modal-body text-center">
		    <h2 class="main-modal-message">Know other awesome people who are excited about startups?</h2>
			</br>
			</br>
			<div class="text-center">
	    		<a href="https://twitter.com/intent/tweet?button_hashtag=StartupHack&text=Receive%20weekly%20curated%20Startup%20lessons%20from%20founders%20straight%20to%20your inbox%20&#151;%20via%20@StartupHackers" class="twitter-hashtag-button" data-lang="en" data-related="StartupHackers" data-size="large">Tweet #StartupHack</a>

		    	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		    	</script>	
		    </div>
	    </div>
	</div>
<% end %>
<!-- End of Modal -->

<div class="lesson-overview-background">
	<div class="container">
		<div class="span6 offset3">

		<% if @admin %>		
				<%= link_to('Create New Lesson', {:action => 'new' }, :class => 'btn btn-large btn-success') %>
		<% end %>

			<% @lesson.each_slice(4) do |show| %>
				<h2 class="lesson-main-headline text-center">
					MONTH <%= show.first.month %>
				</h2>
					<% show.each do |lesson| %>
						<% @loop_counter += 1  %>	
							<div class="row">
								<% if @full_weeks_since_signup  >= @loop_counter %>
									<div class="lesson-overview-block">
										<div class="span1">
											<h2 class="week-number-active week-number-circle-active">
												<%= lesson.week %>
											</h2>
										</div>
										<div class="span11">
											<section class="lesson-headline space">
													<%= link_to(lesson.weekly_tagline, {:action => 'show', :id => lesson.id}, :class => 'lesson-headline-hover') %>
											</section>
										</div>
									</div>
								<% else %>
									<div class="lesson-overview-block">
										<div class="span1">
											<h2 class="week-number-inactive week-number-circle-inactive">
												<%= lesson.week %>
											</h2>
										</div>
										<div class="span11">
											<section class="lesson-headline space">			
												<section class="inactive-link">
													<%= lesson.weekly_tagline %>
												</section>
											</section>
										</div>
									</div>								
								<% end %>
							</div>
			
						<% if @admin %>
								<%= link_to('Edit Lesson', {:action => 'edit', :id => lesson.id }, :class => 'btn btn-mini') %>
								<%= link_to('Delete Lesson', {:action => 'destroy', :id => lesson.id }, :method => 'delete', :confirm => 'Are you sure you want to delete this lesson?', :class => 'btn btn-mini btn-danger') %>
						<% end %>
					<% end %>
				<hr class="hr_shadow_lesson">
				<hr class="hr_shadow_lesson2">
			<% end %>
			
		</div>
	</div>
</div>








 

app/views/lessons/new.html.erb
<div class="container">

  <h1>Create a new Lesson</h1>

<%= simple_form_for @lesson, :url => {:action => 'create'}, :method => 'post', :html => {:class => 'form-horizontal', :multipart => true } do |f| %>

  <%= render(:partial => 'lesson_form_new', :locals => {:f => f}) %>

  <%= f.button :submit, class: "btn btn-primary", value: "Create Lesson" %>
<% end %>

</div>

app/views/lessons/show.html.erb
<div class="background-lesson-detail">
	<div class="container">
		<section class="span6 offset3 text-center lesson_summary">

				<h1 class="lesson-week">
					Week <%= @lesson.week %>
				</h1>
				<h3 class="lesson-main-headline"><%= @lesson.main_headline %></h3>
				<article class="curator_block">
					<p><%= image_tag(@lesson.curator_url(:curator).to_s, :class => 'curator-shots') %></p>
					<h3><%= @lesson.curator_name %></h3>
					<h4><%= @lesson.curator_organization %></h4>
				</article>
				<div class="span">
					<p><%= @lesson.description %></p>
				</div>
		</section>
	</div>
</div> <!-- end of lesson detail background -->

	<section class= "lesson-plan-section">
		<div class="span6 offset3">
			<h1 class="text-center lesson-plan-headline">LESSON PLAN</h1>
			<article class="lesson_block">
				<h1>1</h1>
				<hr>
				<h2><%= link_to(@lesson.first_ressource_headline, @lesson.first_ressource_headline_link, :class => 'no-style-link-lesson', target: "_blank") %></h2>
				<p><%= @lesson.first_ressource_text %></p>
				<task class="task">TASK: </task><p><%= @lesson.first_ressource_task %></p>
			</article>

			<article class="lesson_block">
				<h1>2</h1>
				<hr>
				<h2><%= link_to(@lesson.second_ressource_headline, @lesson.second_ressource_headline_link, :class => 'no-style-link-lesson', target: "_blank") %></h2>
				<p><%= @lesson.second_ressource_text%></p>
				<task class="task">TASK: </task><p><%= @lesson.second_ressource_task %></p>		
			</article>

			<article class="lesson_block">
				<h1>3</h1>
				<hr>
				<h2><%= link_to(@lesson.third_ressource_headline, @lesson.third_ressource_headline_link, :class => 'no-style-link-lesson', target: "_blank") %></h2>
				<p><%= @lesson.third_ressource_text%></p>
				<task class="task">TASK: </task><p><%= @lesson.third_ressource_task %></p>		
			</article>

			<article class="lesson_block">
				<h1>4</h1>
				<hr>
				<h2><%= link_to(@lesson.fourth_ressource_headline, @lesson.fourth_ressource_headline_link, :class => 'no-style-link-lesson', target: "_blank") %></h2>
				<p><%= @lesson.fourth_ressource_text%></p>
				<task class="task">TASK: </task><p><%= @lesson.fourth_ressource_task %></p>
			</article>
		</div>
	</section>
	
	

	<div class="span5 offset3">
		<% if @admin %>
		<h4>Awesome, you're an admin - go ahead and edit or delete this lesson</h4>
		<%= link_to('Edit Lesson', {:action => 'edit', :id => @lesson.id }, :class => 'btn btn-mini') %>
		<%= link_to('Delete Lesson', {:action => 'destroy', :id => @lesson.id }, :method => 'delete', :confirm => 'Are you sure you want to delete this lesson?', :class => 'btn btn-mini btn-danger') %>
		<% end %>
	</div>

</div>
</div>

app/views/lessons/testing.hmtl.erb
testng this branch
 again
 isaac

app/views/subscriber/index.html.erb
<section class="sign-up-background">
	<section class="span8 offset2 text-center main-message-box">
		<h2 class="main-message">An Easy to Follow Course for Entrepreneurs in the Startup World</h2>
	</section>
	<section class="span6 offset3 text-center signup sign-up-well">
		<%= simple_form_for :subscriber, :url => {:action => 'create'}, class: "form_field", :method => 'post', :html => {:class => 'form-horizontal' } do |f| %>
		<%= f.error_notification %>
		<div class="email_button_pair">
		<%= f.input :email, label: false, placeholder: 'We never share your email', :html => { :class=>'input-xlarge'}, wrapper_html: { class: 'input-append' }%>

		<%= f.button :submit, class: "btn btn-success btn-large custom-button", value: "SIGN UP"  %>
		<% end %>
		</div>
	</section>
	<section class="span6 offset3 text-center">
		<h2 class="secondary-message">The path from idea to success is paved with the work of people who have done it before. Learn from the best minds in the startup world today through weekly curated lessons.</h2>
	</section>
	</div>
	</div>
</section>
<!-- What you get Section -->
<section class="marketing-background">
	<div class="container">
		<div class="row">
			<h1 class="marketing-message text-center">FEATURES</h1>
			<div class="text-center">
				<div class="span4">
					<%= image_tag('book.png', :class => 'index-icon') %>
					<h2 class="secondary-marketing-message"><strong>A structured roadmap</strong> to get you from nothing to a solid and executable plan building and scaling your startup</h2>
				</div>
				<div class="span4">
					<%= image_tag('check.png', :class => 'index-icon') %>
					<h2 class="secondary-marketing-message"><strong>The best content on the web</strong>, curated for you by startup experts, so you can stop reading the wrong stuff</h2>
				</div>
				<div class="span4">
					<%= image_tag('pencil.png', :class => 'index-icon') %>
					<h2 class="secondary-marketing-message"><strong>Weekly tasks</strong> so you can learn by doing and keep executing on what matters most: Building your Startup</h2>
				</div>				
			</div>
		</div>
	</div>
</section>
<!-- END // What you get Section -->

<!-- Founding Team Section -->
<section class="team-background">
	<hr class="hr_shadow_team">
	<hr class="hr_shadow_team2">
	<div class="container">
		<div class="row">
			<h1 class="team-header text-center">TEAM</h1>
			<div class="text-center">
				<div class="span3">
					<%= image_tag('marco_bw_s.png', :class => 'team-shots') %>
					<h1 class="team-name">Marco Morawec</h1>
					<hr class="hr_shadow_founders">
					<h2 class="team-job">Web Developer</h2>
					<%= link_to image_tag('twi_s_b.png', :class => 'social_img'), "http://www.twitter.com/marcomorawec", target: "_blank" %>
					<%= link_to image_tag('li_s_b.png', :class => 'social_img'), "http://www.linkedin.com/in/marcomorawec", target: "_blank" %>
					<%= link_to image_tag('git_s_b.png', :class => 'social_img'), "https://github.com/MarcoMorawec", target: "_blank" %>
				</div>
				<div class="span3">
					<%= image_tag('sara_bw_s.png', :class => 'team-shots') %>
					<h1 class="team-name">Sara Garver</h1>
					<hr class="hr_shadow_founders">
					<h2 class="team-job">Business Evangelist</h2>
					<%= link_to image_tag('twi_s_b.png', :class => 'social_img'), "https://twitter.com/skg8d", target: "_blank" %>
					<%= link_to image_tag('li_s_b.png', :class => 'social_img'), "http://www.linkedin.com/in/saragarver", target: "_blank" %>
				</div>		
				<div class="span3">
					<%= image_tag('emily_bw_s.png', :class => 'team-shots') %>
					<h1 class="team-name">Emily Mills</h1>
					<hr class="hr_shadow_founders">
					<h2 class="team-job">Visual & UX Designer</h2>
					<%= link_to image_tag('twi_s_b.png', :class => 'social_img'), "http://www.twitter.com/emily_mills", target: "_blank" %>
					<%= link_to image_tag('li_s_b.png', :class => 'social_img'), "http://www.linkedin.com/in/emilymills2", target: "_blank" %>
				</div>
				<div class="span3">
					<%= image_tag('Isaac_bw_s.png', :class => 'team-shots') %>
					<h1 class="team-name">Isaac Girard</h1>
					<hr class="hr_shadow_founders">
					<h2 class="team-job">Front-end Developer</h2>
					<%= link_to image_tag('twi_s_b.png', :class => 'social_img'), "https://twitter.com/igirard", target: "_blank" %>
					<%= link_to image_tag('li_s_b.png', :class => 'social_img'), "http://www.linkedin.com/in/igirard", target: "_blank" %>
				</div>
			</div>
		</div>
	</div>
</section>